server.port: 8521

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/qasys_core
        username: root
        password: 4258
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
mybatis:
    type-handlers-package: com.example.typehandler
    mapper-locations: /mapper/*.xml

# Spring boot application
spring.application.name: dubbo-auto-configuration-provider-demo
  # Base packages to scan Dubbo Component: @org.apache.service.config.annotation.Service
dubbo.scan.base-packages: com.ps
  # Dubbo Application
  ## The default value of service.application.name is ${spring.application.name}
  ## service.application.name=${spring.application.name}
  # Dubbo Protocol
dubbo.protocol.name: dubbo
dubbo.protocol.port: 8562
service.application.name: shazi
  ## Dubbo Registry
dubbo.registry.address: zookeeper://192.168.3.55:2181/problems
provider:
    # 关闭重试机制
    cluster: failfast
    # 设置服务端响应客户端的超时时间
    timeout: 150000
#dubbo.provider.loadbalance=roundrobin
#dubbo.provider.validation=true








